
// FACEBOOK DATA GET
export const GET_FB_DATA_PENDING = "GET_FB_DATA_PENDING"
export const GET_FB_DATA_FULLFILLED = "GET_FB_DATA_FULLFILLED"
export const GET_FB_DATA_REJECTED = "GET_FB_DATA_REJECTED"

// FACEBOOK DATA GET
export const CREATE_FB_DATA_PENDING = "CREATE_FB_DATA_PENDING"
export const CREATE_FB_DATA_FULLFILLED = "CREATE_FB_DATA_FULLFILLED"
export const CREATE_FB_DATA_REJECTED = "CREATE_FB_DATA_REJECTED"


// FACEBOOK DATA GET
export const DELETE_FB_DATA_PENDING = "DELETE_FB_DATA_PENDING"
export const DELETE_FB_DATA_FULLFILLED = "DELETE_FB_DATA_FULLFILLED"
export const DELETE_FB_DATA_REJECTED = "DELETE_FB_DATA_REJECTED"


// FACEBOOK DATA GET
export const EDIT_FB_DATA_PENDING = "EDIT_FB_DATA_PENDING"
export const EDIT_FB_DATA_FULLFILLED = "EDIT_FB_DATA_FULLFILLED"
export const EDIT_FB_DATA_REJECTED = "EDIT_FB_DATA_REJECTED"


